import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { AuthProvider } from "@/contexts/AuthContext";
=======
>>>>>>> 1dcfe17880d6c3c99c4bdce410965f224500cc3d

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "占いの小窓 | LINE公式アカウント有料チャットシステム",
  description: "占い師とのチャット相談をポイント制で提供するLINE公式アカウントシステム",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 1dcfe17880d6c3c99c4bdce410965f224500cc3d
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<<<<<<< HEAD
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
=======
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> 1dcfe17880d6c3c99c4bdce410965f224500cc3d
      </body>
    </html>
  );
}
